# Generated by Django 4.1.6 on 2023-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=8, unique=True, verbose_name='Уникальная строка идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Датиа и время создания')),
                ('body', models.TextField(max_length=2000, verbose_name='Текст записи')),
                ('active', models.BooleanField(default=True, verbose_name='Статус записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
